# Generated by Django 4.2.1 on 2023-12-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
