services:  - type: web    
name: my-django-app    
env: python    
buildCommand: pip install -r cart/requirements.txt    
startCommand: waitress-serve --host=0.0.0.0 --port=8000 cart.cart.wsgi:application    
rootDirectory: cart    
instances: 1    
plan: starter